---
title: "Udpipe"
author: "Kirill Mukhin"
date: "12 11 2020"
output: html_document
---

```{r message = F, warning = F}
library(ggplot2)
library(dplyr)
library(udpipe)
library(readr)
library(readxl)
library(tidyverse)

stress <- read_tsv("all_accents.tsv") %>%
  dplyr::rename(token = `-де`,
                stress = `-д^е`)

zaliznyak_all_forms <- read_delim("D:/HSE Study Club/Work Files/IRLI RAN/zaliznyak_all_forms.txt", ";", escape_double = FALSE, trim_ws = TRUE) %>%
  mutate(`а#а` = substr(`а#а`, start = str_locate(`а#а`, "#")[,1] + 1, stop = str_length(`а#а`))) %>%
  tidytext::unnest_tokens(word, `а#а`) %>%
  rename(stress = word) %>%
  mutate(stress = ifelse(str_detect(stress, "'") == TRUE, stress,
                         str_c(stress, "'")),
         word = str_replace(stress, "'", "")) %>%
  distinct()

zaliznyak_all_forms <- zaliznyak_all_forms[,c(2,1)]

df <- read_excel("Table2_All_Lines.xlsx")
df_goal <- read_excel("Table3_All_Lines_Grammar_New.xlsx")
udmodel <- udpipe_load_model(file = "russian-syntagrus-ud-2.5-191206.udpipe")
```



```{r warning = F}
x = udpipe(df$LineText, object = udmodel) %>% filter(upos != "PUNCT") %>% dplyr::select(-paragraph_id, -sentence_id, -xpos, -feats, -dep_rel, -deps, -misc)
#vowels = c("а", "е", "ё", "и", "о", "у", "ы", "э", "ю", "я")

y <- x %>%
  mutate(v1 = regexpr('[аеёиоуыэюя]', str_to_lower(sentence)),
         t1 = str_to_lower(substr(x$sentence, start = v1 + 1, stop = str_length(sentence))),
         
         v2 = ifelse(v1 %in% c(-1,0),
                     -1,
                     ifelse(t1 == "",
                            -1,
                            regexpr('[аеёиоуыэюя]', t1) + v1)),
         t2 = ifelse(t1 == "",
                     "",
                     ifelse(str_detect(substr(t1, start = v2 - v1 + 1, stop = str_length(t1)), '[аеёиоуыэюя]') == FALSE,
                            "",
                            substr(t1, start = v2 - v1 + 1, stop = str_length(t1)))),
         
         v3 = ifelse(v2 %in% c(-1,0),
                     -1,
                     ifelse(t2 == "", -1, regexpr('[аеёиоуыэюя]', t2) + v2)),
         t3 = ifelse(t2 == "",
                     "",
                     ifelse(str_detect(substr(t2, start = v3 - v2 + 1, stop = str_length(t2)), '[аеёиоуыэюя]') == FALSE,
                            "",
                            substr(t2, start = v3 - v2 + 1, stop = str_length(t2)))),
         
         v4 = ifelse(v3 %in% c(-1,0),
                     -1,
                     ifelse(t3 == "", -1, regexpr('[аеёиоуыэюя]', t3) + v3)),
         t4 = ifelse(t3 == "",
                     "",
                     ifelse(str_detect(substr(t3, start = v4 - v3 + 1, stop = str_length(t3)), '[аеёиоуыэюя]') == FALSE,
                            "",
                            substr(t3, start = v4 - v3 + 1, stop = str_length(t3)))),
         
         v5 = ifelse(v4 %in% c(-1,0),
                     -1,
                     ifelse(t4 == "", -1, regexpr('[аеёиоуыэюя]', t4) + v4)),
         t5 = ifelse(t4 == "",
                     "",
                     ifelse(str_detect(substr(t4, start = v5 - v4 + 1, stop = str_length(t4)), '[аеёиоуыэюя]') == FALSE,
                            "",
                            substr(t4, start = v5 - v4 + 1, stop = str_length(t4)))),
         
         v6 = ifelse(v5 %in% c(-1,0),
                     -1,
                     ifelse(t5 == "", -1, regexpr('[аеёиоуыэюя]', t5) + v5)),
         t6 = ifelse(t5 == "",
                     "",
                     ifelse(str_detect(substr(t5, start = v6 - v5 + 1, stop = str_length(t5)), '[аеёиоуыэюя]') == FALSE,
                            "",
                            substr(t5, start = v6 - v5 + 1, stop = str_length(t5)))),
         
         v7 = ifelse(v6 %in% c(-1,0),
                     -1,
                     ifelse(t6 == "", -1, regexpr('[аеёиоуыэюя]', t6) + v6)),
         t7 = ifelse(t6 == "",
                     "",
                     ifelse(str_detect(substr(t6, start = v7 - v6 + 1, stop = str_length(t6)), '[аеёиоуыэюя]') == FALSE,
                            "",
                            substr(t6, start = v7 - v6 + 1, stop = str_length(t6)))),
         
         v8 = ifelse(v7 %in% c(-1,0),
                     -1,
                     ifelse(t7 == "", -1, regexpr('[аеёиоуыэюя]', t7) + v7)),
         t8 = ifelse(t7 == "",
                     "",
                     ifelse(str_detect(substr(t7, start = v8 - v7 + 1, stop = str_length(t7)), '[аеёиоуыэюя]') == FALSE,
                            "",
                            substr(t7, start = v8 - v7 + 1, stop = str_length(t7)))),
         
         v9 = ifelse(v8 %in% c(-1,0),
                     -1,
                     ifelse(t8 == "", -1, regexpr('[аеёиоуыэюя]', t8) + v8)),
         t9 = ifelse(t8 == "",
                     "",
                     ifelse(str_detect(substr(t8, start = v9 - v8 + 1, stop = str_length(t8)), '[аеёиоуыэюя]') == FALSE,
                            "",
                            substr(t8, start = v9 - v8 + 1, stop = str_length(t8)))),
         
         token = str_to_lower(token)) %>%
  
  left_join(stress, by = c("token")) %>%
  mutate(position = regexpr("[`^`]", stress) + start - 1,
         Ictus1 = ifelse(v2 == position & upos != "CCONJ",
                         upos, NA),
         Ictus2 = ifelse(v4 == position & upos != "CCONJ",
                         upos, NA),
         Ictus3 = ifelse(v6 == position & upos != "CCONJ",
                         upos, NA),
         Ictus4 = ifelse(v8 == position & upos != "CCONJ",
                         upos, NA)) %>% 
  
  dplyr::select(doc_id, Ictus1, Ictus2, Ictus3, Ictus4) %>%
  group_by(doc_id) %>% 
  summarise_all(funs(trimws(paste(., collapse = '')))) %>%
  mutate(Ictus1 = str_replace_all(Ictus1, "NA", ""),
         Ictus2 = str_replace_all(Ictus2, "NA", ""),
         Ictus3 = str_replace_all(Ictus3, "NA", ""),
         Ictus4 = str_replace_all(Ictus4, "NA", "")) %>%
  mutate(Ictus1 = ifelse(Ictus1 == "", NA, Ictus1),
         Ictus2 = ifelse(Ictus2 == "", NA, Ictus2),
         Ictus3 = ifelse(Ictus3 == "", NA, Ictus3),
         Ictus4 = ifelse(Ictus4 == "", NA, Ictus4)) %>%
  left_join((x %>% dplyr::count(doc_id, sentence) %>% dplyr::select(-n)), by = c("doc_id"))

y[is.na(y)] <- "0"

y = y %>%
  mutate(RhythmFrom = ifelse(Ictus1 != "0" & Ictus2 != "0" & Ictus3 != "0" & Ictus4 != "0", "1",
                      ifelse(Ictus1 == "0" & Ictus2 != "0" & Ictus3 != "0" & Ictus4 != "0", "2",
                      ifelse(Ictus1 != "0" & Ictus2 == "0" & Ictus3 != "0" & Ictus4 != "0", "3",
                      ifelse(Ictus1 != "0" & Ictus2 != "0" & Ictus3 == "0" & Ictus4 != "0", "4",
                      ifelse(Ictus1 != "0" & Ictus2 == "0" & Ictus3 == "0" & Ictus4 != "0", "5",
                      ifelse(Ictus1 == "0" & Ictus2 != "0" & Ictus3 == "0" & Ictus4 != "0", "6",
                      ifelse(Ictus1 == "0" & Ictus2 == "0" & Ictus3 != "0" & Ictus4 != "0", "7",
                      ifelse(Ictus1 == "0" & Ictus2 == "0" & Ictus3 == "0" & Ictus4 != "0", "8", NA)))))))),
         doc_id = as.integer(str_replace(doc_id, "doc", ""))) %>%
  arrange(doc_id) %>%
  mutate(LineID = 1:nrow(y)) %>%
  dplyr::select(-doc_id) %>%
  dplyr::rename(LineText = sentence)

y <- y[,c(7,5,1,2,3,4,6)]

y
```

rf 7 - первые две 0, остальные - сл (и велосипедист летит)
rf 8 - три пропуска, 4 удар (я человеконенавистник)

!CCONJ, SCONJ, PART, ADP - не учитываем в Ictus (односложные)
HMS - полнозначные слова (не служебные и не местоимения - PRON, DET) стоят не на сильной позиции - нечетные слоги! Записываем стопу ямба (1 (1) / 2 (3) / 3 (5) / 4 (7), могут складываться - 1234 или 123 и т.д.)
Во всех нечетных - 9 слогов, а в четных - 8.

```{r}
# зелязняк не работает
x %>% mutate(token = str_to_lower(token)) %>% left_join(zaliznyak, by = c("token")) %>% mutate(position = regexpr("[`'`]", stress) - 1)

# а деятель гитхаба - очень даже хорошо
x %>% mutate(token = str_to_lower(token)) %>%
  left_join(stress, by = c("token")) %>%
  mutate(position = regexpr("[`^`]", stress) + start - 1) %>%
  dplyr::select(sentence, token, stress, position)

table(x$upos)
```


```{r}
y %>% full_join(df_goal, by = "LineID") %>% select(-HMS, -NoT, -NoS, -TextID) %>%
  mutate(i1 = ifelse(Ictus1.x == Ictus1.y, 1, 0),
         i2 = ifelse(Ictus2.x == Ictus2.y, 1, 0),
         i3 = ifelse(Ictus3.x == Ictus3.y, 1, 0),
         i4 = ifelse(Ictus4.x == Ictus4.y, 1, 0)) %>%
  select(i1, i2, i3, i4) %>%
  na.omit() %>% 
  mutate(i1_sum = sum(i1),
         i2_sum = sum(i2),
         i3_sum = sum(i3),
         i4_sum = sum(i4),
         accuracy = (i1_sum + i2_sum + i3_sum + i4_sum) / 1440) %>%
  select(i1_sum, i2_sum, i3_sum, i4_sum, accuracy) %>%
  head(1)

y %>% full_join(df_goal, by = "LineID") %>% select(-HMS, -NoT, -NoS, -TextID)
```


















# свалка

```{r}
pos = x %>%
  spread(term_id, upos) %>%
  select(-start, -end, -token_id, -lemma, -head_token_id, -token)
pos

x = x %>% select(doc_id, sentence) %>% filter(duplicated(doc_id) == FALSE)

for (i in 3:11){
  y = pos %>% filter(is.na(pos[,i]) == FALSE) %>% select_if(~sum(!is.na(.)) > 0) %>% select(-sentence)
  x = x %>% full_join(y, by = "doc_id")
  print(y)
}
```

